#include "../../../include/tile.h"
#include "../../../include/tile/tile_init_helper.h"
#include <raylib.h>
#include <stdbool.h>

void simple_tiles_tile_init() {
  TILE_TYPE_INIT(TILE_WORKSTATION, TILE_LAYER_TOP, NULL, "workstation", TEX_IDS[TEX_WORKSTATION], TILE_PROPS_DEFAULT_WITH_COLOR(BROWN));
  TILE_TYPE_INIT(TILE_OVEN, TILE_LAYER_TOP, NULL, "tall_oven", TEX_IDS[TEX_TALL_OVEN], .tile_props = TILE_PROPS_DEFAULT_WITH_COLOR(GRAY), .width = 16, .height = 32);
  TILE_TYPE_INIT(TILE_TREE, TILE_LAYER_TOP, NULL, "tree_5", TEX_IDS[TEX_ERR], .tile_props = TILE_PROPS_DEFAULT_WITH_COLOR(BROWN), .width = 48, .height = 80);
  TILE_TYPE_INIT(TILE_TREE_STUMP, TILE_LAYER_TOP, NULL, "tree_stump",  TEX_IDS[TEX_TREE], TILE_PROPS_DEFAULT_WITH_COLOR(BROWN), .width = 48);
  TILE_TYPE_INIT(TILE_CHEST, TILE_LAYER_TOP, NULL, "chest", TEX_IDS[TEX_CHEST], TILE_PROPS_DEFAULT_WITH_COLOR(BROWN));
  TILE_TYPE_INIT(TILE_DUNGEON_PORTAL, TILE_LAYER_TOP, NULL, "dungeon_portal", TEX_IDS[TEX_DUNGEON_PORTAL], TILE_PROPS_DEFAULT_WITH_COLOR(BROWN));
}
