#include "../../include/tile.h"
#include "../../include/tile/tile_init_helper.h"
#include <raylib.h>
#include <stdbool.h>

void simple_tiles_tile_init() {
  TILE_TYPE_INIT(TILE_WORKSTATION, TILE_LAYER_TOP, NULL, "workstation", TILE_PROPS_DEFAULT_WITH_COLOR(BROWN));
  TILE_TYPE_INIT(TILE_OVEN, TILE_LAYER_TOP, NULL, "tall_oven", TILE_PROPS_DEFAULT_WITH_COLOR(GRAY));
  TILE_TYPE_INIT(TILE_TREE, TILE_LAYER_TOP, NULL, "tree_5", TILE_PROPS_DEFAULT_WITH_COLOR(BROWN));
  TILE_TYPE_INIT(TILE_TREE_STUMP, TILE_LAYER_TOP, NULL, "tree_stump", TILE_PROPS_DEFAULT_WITH_COLOR(BROWN));
  TILE_TYPE_INIT(TILE_CHEST, TILE_LAYER_TOP, NULL, "chest", TILE_PROPS_DEFAULT_WITH_COLOR(BROWN));
}
